//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int clientId { get; set; }
        public int clientDocumentTypeId { get; set; }
        public string clientDocumentNumber { get; set; }
        public string clientName { get; set; }
        public string clientAddress { get; set; }
        public string clientEmail { get; set; }
        public string clientPhoneNumber { get; set; }
        public Nullable<int> clientStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual cstate cstate { get; set; }
        public virtual Document_Type Document_Type { get; set; }
    }
}
