//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Purchase = new HashSet<Purchase>();
            this.Concept_Sale = new HashSet<Concept_Sale>();
        }
    
        public int productId { get; set; }
        public int productCategoryId { get; set; }
        public Nullable<int> productCode { get; set; }
        public string productName { get; set; }
        public decimal productSellingPrice { get; set; }
        public Nullable<int> productStock { get; set; }
        public Nullable<decimal> productCost { get; set; }
        public Nullable<int> productStateId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concept_Sale> Concept_Sale { get; set; }
        public virtual cstate cstate { get; set; }
    }
}
