//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Concept_Sale = new HashSet<Concept_Sale>();
        }
    
        public int saleId { get; set; }
        public int saleClientId { get; set; }
        public int saleVendorId { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
        public Nullable<decimal> saleDiscount { get; set; }
        public decimal saleTotal { get; set; }
        public int saleStateId { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concept_Sale> Concept_Sale { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual cstate cstate { get; set; }
    }
}
