//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int supplierId { get; set; }
        public int supplierNit { get; set; }
        public string supplierName { get; set; }
        public string supplierAddress { get; set; }
        public string supplierPhoneNumber { get; set; }
        public string supplierCity { get; set; }
        public string supplierWebpage { get; set; }
        public Nullable<int> supplierStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
        public virtual cstate cstate { get; set; }
    }
}
