//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Sale = new HashSet<Sale>();
        }
    
        public int vendorId { get; set; }
        public int vendorDocumentTypeId { get; set; }
        public string vendorDocumentTypeNumber { get; set; }
        public string vendorName { get; set; }
        public string vendorAddress { get; set; }
        public string vendorEmail { get; set; }
        public string vendorPhoneNumber { get; set; }
        public Nullable<int> vendorStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual cstate cstate { get; set; }
        public virtual Document_Type Document_Type { get; set; }
    }
}
