//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelService
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Sale
    {
        public int saleId { get; set; }
        public string Client { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Total { get; set; }
    }
}
